### PR TITLE
XInput Controller OSC

### PR DESCRIPTION
**Pull request by qbitzvr**
I hacked together a quick test to use an XInput Controller over OSC. Would appreciate a review :)

### CODE REVIEW

**Comment by qbitzvr** [comment]
I'm not sure how to build this correctly. I followed the build commands in powershell but I get this error when I run `ThumbParamsOSC.exe`:
```
Traceback (most recent call last):
  File "C:\Users\Qbitz\Documents\GitHub\VRCThumbParamsOSC\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Users\Qbitz\Documents\GitHub\VRCThumbParamsOSC\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "main.py", line 9, in <module>
  File "C:\Users\Qbitz\Documents\GitHub\VRCThumbParamsOSC\src\osc.py", line 2, in <module>
    from tinyoscquery.queryservice import OSCQueryService
  File "C:\Users\Qbitz\Documents\GitHub\VRCThumbParamsOSC\src\tinyoscquery\queryservice.py", line 1, in <module>
    from zeroconf import ServiceInfo, Zeroconf
ImportError: dynamic module does not define module export function (PyInit_zeroconf)
```

**Comment by I5UCC** [comment]
I've also been getting the same error, even without your changes. This does seem to be related to zeroconf in some way, as i havent made many changes in recent time. I'm gonna try and look into it, maybe switch building methodology to circumvent this somehow

**Comment by I5UCC** [comment]
I've observed that building has become impossible since version 0.122.1 of zeroconf. After examining the release notes, it appears that they are skipping wheel builds for end-of-life (EOL) Python versions and older Pythons with aarch64 architecture. This is perplexing because I'm building for Python 3.11, which is not EOL, and we're not targeting ARM architecture either. I plan to open an issue in the zeroconf repository to seek clarification. Meanwhile, I've temporarily specified that version in the requirements.txt to resolve the building process. In commit: https://github.com/I5UCC/VRCThumbParamsOSC/commit/6cadaee8f3ef94a25efb1823703f41415739ec30

**Comment by I5UCC** [comment]
Code looks good like this so far, merged into dev! Thanks for the contribution so far!

**Comment by qbitzvr** [comment]
Cool, thanks!

**Pull request merged**
